export const DEFAULT_PORTS = {
  WEB: 3000,
  API: 3001,
  AI_SERVICE: 8100,
  POSTGRES: 5432,
  REDIS: 6379,
  PROMETHEUS: 9090,
  GRAFANA: 3100,
  LOKI: 3200,
} as const;

export const TELEMETRY_THRESHOLDS = {
  PACKET_LOSS_WARNING_PERCENT: 2.0,
  PACKET_LOSS_CRITICAL_PERCENT: 5.0,
  LATENCY_WARNING_MS: 150.0,
  LATENCY_CRITICAL_MS: 250.0,
  JITTER_WARNING_MS: 30.0,
  JITTER_CRITICAL_MS: 50.0,
  CPU_WARNING_PERCENT: 75.0,
  CPU_CRITICAL_PERCENT: 90.0,
  POP_UTILIZATION_WARNING: 70.0,
  POP_UTILIZATION_HIGH: 80.0,
  POP_UTILIZATION_CRITICAL: 90.0,
} as const;

export const ROLES_LIST = [
  'PROVIDER',
  'PROVIDER_ADMIN',
  'NOC_OPERATOR',
  'TENANT_ADMIN',
  'TENANT_OPERATOR',
  'AUDITOR',
  'READ_ONLY',
] as const;
